const mockRandomFood = {
  meals: [
    {
      idMeal: '52817',
      strMeal: 'Stovetop Eggplant With Harissa, Chickpeas, and Cumin Yogurt',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'American',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/yqwtvu1487426027.jpg',
      strTags: 'Vegetarian',
      strYoutube: 'https://www.youtube.com/watch?v=uYB-1xJp4lg',
      strIngredient1: 'Olive Oil',
      strIngredient2: 'Egg Plants',
      strIngredient3: 'Harissa',
      strIngredient4: 'Chickpeas',
      strIngredient5: 'Cherry Tomatoes',
      strIngredient6: 'Greek yogurt',
      strIngredient7: 'Ground cumin',
      strIngredient8: 'Parsley',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '4 tablespoons',
      strMeasure2: '6 small',
      strMeasure3: '½ tablespoon',
      strMeasure4: '1 can',
      strMeasure5: '2 cups halved',
      strMeasure6: '1 1/2 cups',
      strMeasure7: '1 tablespoon',
      strMeasure8: '½ cup ',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.seriouseats.com/2014/09/one-pot-wonders-stovetop-eggplant-harissa-chickpeas-cumin.html',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export default mockRandomFood;
