const mockRandomDrink = {
  drinks: [
    {
      idDrink: '17120',
      strDrink: 'Brain Fart',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Punch / Party Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Punch bowl',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rz5aun1504389701.jpg',
      strIngredient1: 'Everclear',
      strIngredient2: 'Vodka',
      strIngredient3: 'Mountain Dew',
      strIngredient4: 'Surge',
      strIngredient5: 'Lemon juice',
      strIngredient6: 'Rum',
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 fifth ',
      strMeasure2: '1 fifth Smirnoff red label ',
      strMeasure3: '2 L ',
      strMeasure4: '2 L ',
      strMeasure5: '1 small bottle ',
      strMeasure6: '1 pint ',
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-02 23:01:42',
    },
  ],
};

export default mockRandomDrink;
